[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_ENV           = "production"

[context.deploy-preview]
    command = "hugo --gc --minify --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"
