#!/usr/bin/env zsh

name=$1

cd $(dirname $0)

slug=$(print $name | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
slugpath=../content/blog/${slug}
mkdir -p $slugpath

print "\---
title: $name
date: $(node --print "new Date().toISOString()")
description: \"\"
---" > $slugpath/index.md
